### PR TITLE
cleanup the angular integration

### PR DESCRIPTION
**Pull request by tardyp**
in order to integrate properly in angular.js, we need to use a directive.
getting the element through $element.find is subject to race condition and is not supposed to work.

This patch uses a directive, and remove the class style, so that it is more angularish.

### CODE REVIEW

**Comment by tardyp** [comment]
@uglycoyote @rajdeepbharati I also enhanced the readme to clarify all the gulp dev proxy works, and how the directive works.

**Comment by uglycoyote** [comment]
This is great, thanks so much for your contributions.  I don't have a setup currently where I can test it on my end at the moment but I'll accept the changes and test later given that you are obviously doing something with it and that my repo has very low "traffic". 

I'm curious what you and @rajdeepbharati are up to that sparked the sudden interest?  Searched the IRC logs but did not see any conversation about it there.  I'm still in a bit of a hibernation from buildbot development due to the state of our product cycle and the fact that our current buildbot UI setup is working for us but I planned to revisit this repo and the corresponding webpack/typescript efforts later in the year. (Our working version of console-plugin is using a mishmash of coffeescript, and plain-JS/React at the moment.)

**Comment by tardyp** [comment]
@uglycoyote This is for GSoC 2019, Rajdeep is working on making custom dashboard for macport project

**Comment by uglycoyote** [comment]
@tardyp @rajdeepbharati sounds good.  I would love to hear more details about what kind of custom interface you are planning.   I checked out the macports buildbot, it looks like it hasn't been upgraded to buildbot nine yet

**Comment by rajgoesout** [comment]
@uglycoyote I'm planning to upgrade the macports buildbot and then integrate the custom Vue components to it.

**Comment by uglycoyote** [comment]
@rajdeepbharati that sounds great.  I would love to hear more details about what kind of custom Vue components you are planning to integrate in to the macports buildbot.

**Pull request merged**
